version: "3.7"

services:
  database_ignite_unittest_challenge:
    image: postgres
    container_name: database_ignite_unittest_challenge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
